image: mcr.microsoft.com/dotnet/sdk:8.0

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

stages:
  - build-sonar
  - docker-build-dev
  - deploy-dev

build-sonar:
  stage: build-sonar
  tags:
    - gl-runner
  cache:
    policy: pull-push
    key: "sonar-cache-$CI_COMMIT_REF_SLUG"
    paths:
      - "${SONAR_USER_HOME}/cache"
  
  script:
    - apt-get update && apt-get install -y openjdk-17-jre
    - |
      if ! dotnet tool list --global | grep dotnet-sonarscanner; then
        dotnet tool install --global dotnet-sonarscanner
      else
        dotnet tool update --global dotnet-sonarscanner
      fi

    - export PATH="$PATH:$HOME/.dotnet/tools"

    - dotnet sonarscanner begin /k:"astradualsystem_sia-backend_18253daa-02c3-47e6-b818-7d0ec80404d1" /v:"$CI_COMMIT_SHORT_SHA" /d:sonar.token="$SONAR_TOKEN" /d:sonar.host.url="$SONAR_HOST_URL" /d:sonar.exclusions=".gitlab-ci.yml,.gitlab-ci/**/*,*.gitlab-ci.yml,Dockerfile*,*.dockerfile,.dockerignore,docker-compose*.yml"

    - dotnet build --no-incremental

    - dotnet sonarscanner end /d:sonar.token="$SONAR_TOKEN"

  allow_failure: false
  rules:
    - if: $CI_COMMIT_BRANCH == 'dev'

docker-build-dev:
  stage: docker-build-dev
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  tags:
    - gl-runner
  when: on_success
  needs: ["build-sonar"]
  script:
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"username\":\"$DOCKER_USERNAME\",\"password\":\"$DOCKER_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination=$DOCKER_USERNAME/be_siadev:$CI_COMMIT_SHA
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination=$DOCKER_USERNAME/be_siadev:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"

deploy-dev:
  stage: deploy-dev
  when: on_success
  needs: ["docker-build-dev"]
  only: 
    - dev
  image: curlimages/curl:latest
  tags:
    - gl-runner
  services:
    - docker:dind
  script:
    - curl --user Developer:$JENKINS_PWD $JENKINS_DEPLOY_URL
